### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by TechnologyClassroom** [vaughngx4/OpenSMM#1]
I see the license is listed as [ISC](https://github.com/vaughngx4/OpenSMM/blob/a981594b9b2db89b1fb0bdfe45891658da27f9a8/api/app/package.json#L13).  I would recommend using a copyleft license instead as successful permissively licensed projects tend to be used by companies within proprietary projects and they typically never give back.  If you go with copyleft, I would recommend [AGPL-3.0-or-later](https://spdx.org/licenses/AGPL-3.0-or-later.html) or at least GPL-3.0-or-later.  If you stick with a permissive license, I would recommend Apache-2.0.

If you plan on using parts of SocioBoard, you need to match the license of SocioBoard which is GPL-3.0-or-later.

I would further recommend making a license file in the root directory of the repo.  If you create a LICENSE file, this information will be displayed within the first page view for the project. GitHub walks you through it after naming a new file LICENSE.

**Comment by vaughngx4** [comment]
Thank you for this, I didn't even realise that it set a license. Will fix soon.

**Comment by vaughngx4** [comment]
I see you meant it had ISC in node's package.json. I've made changes and added a LICENSE file. :)
